// CrownMe brand tokens for email templates.
// Email body must stay white per platform rules; gold + royal purple accents.

export const brand = {
  gold: '#E0B43A',
  goldDark: '#B8860B',
  royal: '#1A0F2E',
  royalDeep: '#14092B',
  purple: '#6B3FA0',
  ivory: '#FFF8E7',
  borderGold: '#E7C04A',
}

export const HERO_BASE = 'https://crownmemedia.com/__l5e/assets-v1'

export const heroImg = {
  display: 'block',
  width: '100%',
  maxWidth: '560px',
  height: 'auto',
  border: '0',
  outline: 'none',
  textDecoration: 'none',
} as const

export const styles = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily: 'Georgia, "Times New Roman", serif',
    margin: 0,
    padding: 0,
  } as const,
  container: {
    maxWidth: '560px',
    margin: '0 auto',
    padding: '0',
    border: `1px solid ${brand.borderGold}`,
    borderRadius: '16px',
    overflow: 'hidden',
  } as const,
  header: {
    background: `linear-gradient(135deg, ${brand.royal} 0%, ${brand.purple} 100%)`,
    backgroundColor: brand.royal,
    padding: '28px 24px',
    textAlign: 'center' as const,
  } as const,
  brandText: {
    color: brand.gold,
    fontSize: '24px',
    fontWeight: 'bold' as const,
    letterSpacing: '4px',
    margin: 0,
    textTransform: 'uppercase' as const,
  } as const,
  brandTag: {
    color: '#F3E2A9',
    fontSize: '11px',
    letterSpacing: '2px',
    margin: '6px 0 0',
    textTransform: 'uppercase' as const,
  } as const,
  body: {
    padding: '36px 32px 32px',
    backgroundColor: '#ffffff',
    borderTop: `3px solid ${brand.gold}`,
  } as const,
  ornament: {
    textAlign: 'center' as const,
    color: brand.goldDark,
    fontSize: '14px',
    letterSpacing: '6px',
    margin: '0 0 20px',
    lineHeight: '1',
  } as const,
  overline: {
    textAlign: 'center' as const,
    color: brand.goldDark,
    fontSize: '11px',
    fontWeight: 'bold' as const,
    letterSpacing: '4px',
    textTransform: 'uppercase' as const,
    margin: '0 0 10px',
  } as const,
  h1: {
    fontSize: '28px',
    fontWeight: 'bold' as const,
    color: brand.royal,
    margin: '0 0 18px',
    lineHeight: '1.25',
    textAlign: 'center' as const,
    fontFamily: 'Georgia, "Times New Roman", serif',
  } as const,
  text: {
    fontSize: '16px',
    color: '#2f2740',
    lineHeight: '1.65',
    margin: '0 0 20px',
    fontFamily: 'Georgia, "Times New Roman", serif',
    textAlign: 'center' as const,
  } as const,
  link: { color: brand.goldDark, textDecoration: 'underline', fontWeight: 'bold' as const } as const,
  callout: {
    backgroundColor: brand.ivory,
    border: `1px solid ${brand.borderGold}`,
    borderLeft: `4px solid ${brand.gold}`,
    borderRadius: '10px',
    padding: '16px 20px',
    margin: '0 0 24px',
    color: brand.royal,
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: '15px',
    lineHeight: '1.55',
  } as const,
  buttonWrap: {
    textAlign: 'center' as const,
    margin: '8px 0 4px',
  } as const,
  button: {
    backgroundColor: brand.gold,
    backgroundImage: `linear-gradient(135deg, #F4CB5A 0%, ${brand.gold} 50%, ${brand.goldDark} 100%)`,
    color: brand.royalDeep,
    fontSize: '15px',
    fontWeight: 'bold' as const,
    borderRadius: '999px',
    padding: '16px 36px',
    textDecoration: 'none',
    letterSpacing: '2px',
    textTransform: 'uppercase' as const,
    display: 'inline-block',
    border: `1px solid ${brand.goldDark}`,
  } as const,
  code: {
    fontFamily: 'Courier, monospace',
    fontSize: '30px',
    fontWeight: 'bold' as const,
    color: brand.royal,
    letterSpacing: '8px',
    backgroundColor: brand.ivory,
    border: `1px dashed ${brand.borderGold}`,
    borderRadius: '12px',
    padding: '18px 20px',
    textAlign: 'center' as const,
    margin: '0 0 24px',
  } as const,
  hr: {
    border: 'none',
    borderTop: `1px solid ${brand.borderGold}`,
    margin: '28px 0 20px',
    opacity: 0.5,
  } as const,
  footer: {
    fontSize: '12px',
    color: '#8a8194',
    margin: '18px 0 0',
    lineHeight: '1.5',
    fontStyle: 'italic' as const,
    textAlign: 'center' as const,
  } as const,
  signature: {
    fontSize: '13px',
    color: brand.royal,
    margin: '28px 0 0',
    fontWeight: 'bold' as const,
    textAlign: 'center' as const,
    letterSpacing: '2px',
    textTransform: 'uppercase' as const,
  } as const,
}
