// CrownMe brand tokens for email templates.
// Body uses ivory parchment; dark royal footer bar seals the layout.

export const brand = {
  gold: '#E0B43A',
  goldBright: '#F4CB5A',
  goldDark: '#B8860B',
  royal: '#1A0F2E',
  royalDeep: '#0E0620',
  purple: '#6B3FA0',
  purpleGem: '#7B4FB8',
  ivory: '#FBF3DE',
  ivoryDeep: '#F5E9C8',
  borderGold: '#C9A24A',
}

export const HERO_BASE = 'https://crownmemedia.com/__l5e/assets-v1'

export const heroImg = {
  display: 'block',
  width: '100%',
  maxWidth: '560px',
  height: 'auto',
  border: '0',
  outline: 'none',
  textDecoration: 'none',
} as const

export const styles = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily: 'Georgia, "Times New Roman", serif',
    margin: 0,
    padding: 0,
  } as const,
  container: {
    maxWidth: '560px',
    margin: '0 auto',
    padding: '0',
    border: `1px solid ${brand.borderGold}`,
    borderRadius: '16px',
    overflow: 'hidden',
    backgroundColor: brand.ivory,
  } as const,
  header: {
    background: `linear-gradient(135deg, ${brand.royal} 0%, ${brand.purple} 100%)`,
    backgroundColor: brand.royal,
    padding: '28px 24px',
    textAlign: 'center' as const,
  } as const,
  brandText: {
    color: brand.gold,
    fontSize: '24px',
    fontWeight: 'bold' as const,
    letterSpacing: '4px',
    margin: 0,
    textTransform: 'uppercase' as const,
  } as const,
  brandTag: {
    color: '#F3E2A9',
    fontSize: '11px',
    letterSpacing: '2px',
    margin: '6px 0 0',
    textTransform: 'uppercase' as const,
  } as const,
  // Ivory parchment body
  body: {
    padding: '40px 32px 36px',
    backgroundColor: brand.ivory,
    backgroundImage: `radial-gradient(circle at 50% 0%, ${brand.ivoryDeep} 0%, ${brand.ivory} 60%)`,
    textAlign: 'center' as const,
  } as const,
  // Divider row: gold line — purple gem — gold line
  dividerRow: {
    width: '100%',
    margin: '0 auto 18px',
    borderCollapse: 'collapse' as const,
  } as const,
  dividerLine: {
    borderTop: `1px solid ${brand.borderGold}`,
    height: '1px',
    width: '38%',
    opacity: 0.7,
  } as const,
  dividerGem: {
    width: '24px',
    textAlign: 'center' as const,
    color: brand.purpleGem,
    fontSize: '18px',
    lineHeight: '1',
    padding: '0 8px',
  } as const,
  h1: {
    fontSize: '38px',
    fontWeight: 'bold' as const,
    color: brand.royal,
    margin: '4px 0 6px',
    lineHeight: '1.15',
    textAlign: 'center' as const,
    fontFamily: 'Georgia, "Times New Roman", serif',
    letterSpacing: '-0.5px',
  } as const,
  h1Accent: {
    color: brand.goldDark,
    fontStyle: 'italic' as const,
    fontWeight: 'bold' as const,
  } as const,
  text: {
    fontSize: '16px',
    color: '#2f2740',
    lineHeight: '1.6',
    margin: '0 0 18px',
    fontFamily: 'Georgia, "Times New Roman", serif',
    textAlign: 'center' as const,
  } as const,
  link: { color: brand.goldDark, textDecoration: 'underline', fontWeight: 'bold' as const } as const,
  callout: {
    backgroundColor: '#ffffff',
    border: `1px solid ${brand.borderGold}`,
    borderLeft: `4px solid ${brand.gold}`,
    borderRadius: '10px',
    padding: '16px 20px',
    margin: '0 0 24px',
    color: brand.royal,
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: '15px',
    lineHeight: '1.55',
  } as const,
  buttonWrap: {
    textAlign: 'center' as const,
    margin: '14px 0 6px',
  } as const,
  button: {
    backgroundColor: brand.gold,
    backgroundImage: `linear-gradient(180deg, ${brand.goldBright} 0%, ${brand.gold} 55%, ${brand.goldDark} 100%)`,
    color: brand.royalDeep,
    fontSize: '17px',
    fontWeight: 'bold' as const,
    borderRadius: '10px',
    padding: '16px 40px',
    textDecoration: 'none',
    letterSpacing: '0.5px',
    display: 'inline-block',
    border: `1px solid ${brand.goldDark}`,
    boxShadow: `0 4px 0 ${brand.goldDark}, 0 8px 18px rgba(0,0,0,0.25)`,
    fontFamily: 'Georgia, "Times New Roman", serif',
  } as const,
  buttonCrown: {
    color: brand.royalDeep,
    fontSize: '16px',
    margin: '0 10px',
  } as const,
  code: {
    fontFamily: 'Courier, monospace',
    fontSize: '30px',
    fontWeight: 'bold' as const,
    color: brand.royal,
    letterSpacing: '8px',
    backgroundColor: '#ffffff',
    border: `1px dashed ${brand.borderGold}`,
    borderRadius: '12px',
    padding: '18px 20px',
    textAlign: 'center' as const,
    margin: '0 0 24px',
  } as const,
  hr: {
    border: 'none',
    borderTop: `1px solid ${brand.borderGold}`,
    margin: '24px 0 14px',
    opacity: 0.5,
  } as const,
  // Small crown divider between signature and note
  miniCrown: {
    textAlign: 'center' as const,
    color: brand.goldDark,
    fontSize: '14px',
    margin: '20px 0 6px',
    lineHeight: '1',
  } as const,
  signature: {
    fontSize: '13px',
    color: '#6b5a7a',
    margin: '4px 0 0',
    fontStyle: 'italic' as const,
    textAlign: 'center' as const,
  } as const,
  footerNote: {
    fontSize: '12px',
    color: '#8a8194',
    margin: '12px 0 0',
    lineHeight: '1.5',
    fontStyle: 'italic' as const,
    textAlign: 'center' as const,
  } as const,
  // Dark royal footer bar
  darkFooter: {
    backgroundColor: brand.royalDeep,
    backgroundImage: `linear-gradient(180deg, ${brand.royal} 0%, ${brand.royalDeep} 100%)`,
    padding: '22px 24px 20px',
    textAlign: 'center' as const,
    borderTop: `1px solid ${brand.borderGold}`,
  } as const,
  darkFooterRow: {
    width: '100%',
    borderCollapse: 'collapse' as const,
  } as const,
  darkFooterIcon: {
    color: brand.gold,
    fontSize: '18px',
    width: '40px',
    textAlign: 'center' as const,
    lineHeight: '1',
  } as const,
  darkFooterDomain: {
    color: brand.gold,
    fontSize: '15px',
    fontWeight: 'bold' as const,
    letterSpacing: '2px',
    textAlign: 'center' as const,
    fontFamily: 'Georgia, "Times New Roman", serif',
  } as const,
  darkFooterDivider: {
    borderTop: `1px solid ${brand.borderGold}`,
    opacity: 0.35,
    margin: '12px auto 10px',
    width: '60%',
  } as const,
  darkFooterTag: {
    color: brand.gold,
    fontSize: '12px',
    letterSpacing: '6px',
    textTransform: 'uppercase' as const,
    margin: '0',
    textAlign: 'center' as const,
    fontFamily: 'Georgia, "Times New Roman", serif',
  } as const,
  // Legacy alias kept so any older templates importing styles.footer still compile.
  footer: {
    fontSize: '12px',
    color: '#8a8194',
    margin: '12px 0 0',
    lineHeight: '1.5',
    fontStyle: 'italic' as const,
    textAlign: 'center' as const,
  } as const,
  // Legacy ornament + overline aliases (older signup.tsx references them)
  ornament: {
    textAlign: 'center' as const,
    color: brand.purpleGem,
    fontSize: '16px',
    margin: '0 0 12px',
    lineHeight: '1',
  } as const,
  overline: {
    textAlign: 'center' as const,
    color: brand.goldDark,
    fontSize: '11px',
    fontWeight: 'bold' as const,
    letterSpacing: '4px',
    textTransform: 'uppercase' as const,
    margin: '0 0 10px',
  } as const,
}
