-- Restore Data API access to the public-safe profile columns used by profile pages.
-- Column-level grants are used so sensitive/private preference fields remain protected.
GRANT SELECT (
  id,
  username,
  profile_photo_url,
  bio,
  city,
  state,
  country,
  followers_count,
  following_count,
  votes_received,
  votes_given,
  crowns_held,
  crowns_total,
  battle_wins,
  is_suspended,
  created_at,
  updated_at,
  banner_url,
  banner_position_y,
  avatar_position_y,
  liked_posts_public,
  gender,
  pronouns,
  is_private,
  hide_likes,
  hide_comments,
  hide_views,
  posts_visibility,
  links,
  verified,
  verified_at
) ON public.profiles TO anon, authenticated;

-- Preserve authenticated profile editing without allowing anonymous writes.
GRANT UPDATE (
  username,
  profile_photo_url,
  bio,
  city,
  state,
  country,
  banner_url,
  banner_position_y,
  avatar_position_y,
  liked_posts_public,
  first_name,
  last_name,
  gender,
  pronouns,
  is_private,
  hide_likes,
  hide_comments,
  hide_views,
  posts_visibility,
  links,
  locale,
  default_post_visibility,
  default_category,
  default_comments_enabled,
  watermark_enabled,
  autosave_to_camera_roll,
  who_can_tag,
  who_can_mention,
  who_can_dm,
  tag_review_required,
  reduce_motion,
  larger_text,
  high_contrast,
  captions_default_on,
  autoplay_cellular,
  quiet_hours_start,
  quiet_hours_end,
  timezone,
  push_likes,
  push_follows,
  push_comments,
  push_battles,
  default_battle_stake,
  auto_accept_battles_from_follows,
  default_race_scope
) ON public.profiles TO authenticated;

GRANT ALL ON public.profiles TO service_role;