-- Royal Gifts catalog table (read-only for clients)
create table if not exists public.gifts (
  id text primary key,
  name text not null,
  shekel_cost numeric not null,
  tier text not null,
  rarity text not null,
  animation_type text not null,
  icon text not null,
  visibility_boost boolean not null default false,
  trending boolean not null default false,
  top_pick boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.gifts enable row level security;

drop policy if exists "Gifts are viewable by everyone" on public.gifts;
create policy "Gifts are viewable by everyone"
  on public.gifts for select using (true);

create index if not exists idx_gifts_tier on public.gifts(tier);

insert into public.gifts (id, name, shekel_cost, tier, rarity, animation_type, icon, visibility_boost, trending, top_pick) values
('royal_coin_toss', 'Royal Coin Toss', 100, 'low', 'common', 'royal_coin_toss', '🪙', false, false, false),
('gold_dust', 'Gold Dust', 100, 'low', 'common', 'gold_dust', '✨', false, false, false),
('royal_clap', 'Royal Clap', 100, 'low', 'common', 'royal_clap', '👏', false, false, false),
('mini_gem', 'Mini Gem', 100, 'low', 'common', 'mini_gem', '💠', false, false, false),
('royal_scroll', 'Royal Scroll', 200, 'low', 'common', 'royal_scroll', '📜', false, false, false),
('crown_spark', 'Crown Spark', 250, 'low', 'common', 'crown_spark', '💫', false, true, false),
('spark_crown', 'Spark Crown', 200, 'low', 'common', 'spark_crown', '👑', false, false, false),
('royal_quill', 'Royal Quill', 200, 'low', 'common', 'royal_quill', '🪶', false, false, false),
('velvet_bow', 'Velvet Bow', 300, 'low', 'common', 'velvet_bow', '🎀', false, false, false),
('royal_candle', 'Royal Candle', 300, 'low', 'common', 'royal_candle', '🕯️', false, false, false),
('royal_chalice', 'Royal Chalice', 300, 'low', 'common', 'royal_chalice', '🍷', false, false, false),
('royal_rose', 'Royal Rose', 500, 'low', 'common', 'royal_rose', '🌹', false, false, true),
('court_applause', 'Court Applause', 700, 'low', 'common', 'court_applause', '🥂', false, false, false),
('royal_seal', 'Royal Seal', 500, 'low', 'common', 'royal_seal', '📯', false, false, false),
('crown_ribbon', 'Crown Ribbon', 500, 'low', 'common', 'crown_ribbon', '🎗️', false, false, false),
('royal_lantern', 'Royal Lantern', 700, 'low', 'common', 'royal_lantern', '🏮', false, false, false),
('royal_keys', 'Royal Keys', 700, 'low', 'common', 'royal_keys', '🗝️', false, false, false),
('noble_emblem', 'Noble Emblem', 700, 'low', 'common', 'noble_emblem', '🛡️', false, false, false),
('velvet_pillow', 'Velvet Pillow', 900, 'low', 'common', 'velvet_pillow', '🛏️', false, false, false),
('royal_dove', 'Royal Dove', 900, 'low', 'common', 'royal_dove', '🕊️', false, false, false),
('golden_flame', 'Golden Flame', 1000, 'popular', 'rare', 'golden_flame', '🔥', false, true, false),
('crown_burst', 'Crown Burst', 1000, 'popular', 'rare', 'crown_burst', '💥', false, false, false),
('coin_rain', 'Coin Rain', 1000, 'popular', 'rare', 'coin_rain', '🌧️', false, false, false),
('gold_ribbon', 'Gold Ribbon', 1000, 'popular', 'rare', 'gold_ribbon', '🎗️', false, false, false),
('royal_fireworks', 'Royal Fireworks', 2000, 'popular', 'rare', 'royal_fireworks', '🎆', false, true, false),
('mini_crown_drop', 'Mini Crown Drop', 2000, 'popular', 'rare', 'mini_crown_drop', '👑', false, false, false),
('royal_drum', 'Royal Drum', 2000, 'popular', 'rare', 'royal_drum', '🥁', false, false, false),
('royal_trumpet', 'Royal Trumpet', 2000, 'popular', 'rare', 'royal_trumpet', '🎺', false, false, false),
('emerald_shard', 'Emerald Shard', 2000, 'popular', 'rare', 'emerald_shard', '🟢', false, false, false),
('ruby_shard', 'Ruby Shard', 2000, 'popular', 'rare', 'ruby_shard', '🔴', false, false, false),
('treasure_chest', 'Treasure Chest', 3000, 'popular', 'rare', 'treasure_chest', '💰', false, false, true),
('royal_banner', 'Royal Banner', 3000, 'popular', 'rare', 'royal_banner', '🚩', false, false, false),
('golden_harp', 'Golden Harp', 3000, 'popular', 'rare', 'golden_harp', '🎻', false, false, false),
('gem_shower', 'Gem Shower', 3000, 'popular', 'rare', 'gem_shower', '💎', false, false, false),
('royal_crest', 'Royal Crest', 3000, 'popular', 'rare', 'royal_crest', '🛡️', false, false, false),
('royal_carriage', 'Royal Carriage', 5000, 'popular', 'rare', 'royal_carriage', '🛞', false, false, false),
('royal_lion', 'Royal Lion', 5000, 'popular', 'rare', 'royal_lion', '🦁', false, false, false),
('royal_eagle', 'Royal Eagle', 5000, 'popular', 'rare', 'royal_eagle', '🦅', false, false, false),
('crown_fountain', 'Crown Fountain', 5000, 'popular', 'rare', 'crown_fountain', '⛲', false, false, false),
('royal_feast', 'Royal Feast', 5000, 'popular', 'rare', 'royal_feast', '🍗', false, false, false),
('royal_mask', 'Royal Masquerade', 7000, 'popular', 'rare', 'royal_mask', '🎭', false, false, false),
('royal_cape', 'Royal Cape', 7000, 'popular', 'rare', 'royal_cape', '🦸', false, false, false),
('royal_throne_chair', 'Throne Chair', 7000, 'popular', 'rare', 'royal_throne_chair', '🪑', false, false, false),
('royal_griffin', 'Royal Griffin', 9000, 'popular', 'rare', 'royal_griffin', '🦅', false, false, false),
('crown_phoenix', 'Crown Phoenix', 9000, 'popular', 'rare', 'crown_phoenix', '🐦‍🔥', false, false, false),
('crown_pulse', 'Crown Pulse', 10000, 'premium', 'epic', 'crown_pulse', '💜', false, false, false),
('throne_room', 'Throne Room', 10000, 'premium', 'epic', 'throne_room', '🏛️', false, true, false),
('royal_armor', 'Royal Armor', 10000, 'premium', 'epic', 'royal_armor', '🛡️', false, false, false),
('golden_aura', 'Golden Aura', 10000, 'premium', 'epic', 'golden_aura', '🌟', false, false, false),
('crown_ascension', 'Crown Ascension', 10000, 'premium', 'epic', 'crown_ascension', '🪜', false, false, false),
('golden_wings', 'Golden Wings', 15000, 'premium', 'epic', 'golden_wings', '🪽', false, false, false),
('royal_pegasus', 'Royal Pegasus', 15000, 'premium', 'epic', 'royal_pegasus', '🐎', false, false, false),
('royal_dragon', 'Royal Dragon', 15000, 'premium', 'epic', 'royal_dragon', '🐉', false, false, false),
('crown_meteor', 'Crown Meteor', 15000, 'premium', 'epic', 'crown_meteor', '☄️', false, false, false),
('royal_aurora', 'Royal Aurora', 15000, 'premium', 'epic', 'royal_aurora', '🌌', false, false, false),
('throne_rise', 'Throne Rise', 20000, 'premium', 'epic', 'throne_rise', '🪑', false, false, false),
('royal_guard', 'Royal Guard', 20000, 'premium', 'epic', 'royal_guard', '💂', false, false, false),
('crown_steal_attempt', 'Crown Steal', 20000, 'premium', 'epic', 'crown_steal_attempt', '⚔️', false, false, true),
('royal_supernova', 'Royal Supernova', 20000, 'premium', 'epic', 'royal_supernova', '💫', false, false, false),
('crown_serpent', 'Crown Serpent', 20000, 'premium', 'epic', 'crown_serpent', '🐍', false, false, false),
('royal_ascendancy', 'Royal Ascendancy', 25000, 'premium', 'epic', 'royal_ascendancy', '🌠', false, false, false),
('royal_obsidian', 'Obsidian Crown', 25000, 'premium', 'epic', 'royal_obsidian', '🖤', false, false, false),
('royal_diamond_fire', 'Diamond Fire', 25000, 'premium', 'epic', 'royal_diamond_fire', '💎', false, false, false),
('royal_galaxy', 'Royal Galaxy', 25000, 'premium', 'epic', 'royal_galaxy', '🌠', false, false, false),
('crown_titan', 'Crown Titan', 30000, 'premium', 'epic', 'crown_titan', '🗿', false, false, false),
('royal_kraken', 'Royal Kraken', 30000, 'premium', 'epic', 'royal_kraken', '🐙', false, false, false),
('crown_olympus', 'Crown of Olympus', 30000, 'premium', 'epic', 'crown_olympus', '⚡', false, false, false),
('royal_tempest', 'Royal Tempest', 30000, 'premium', 'epic', 'royal_tempest', '🌪️', false, false, false),
('crown_legacy', 'Crown Legacy', 35000, 'premium', 'epic', 'crown_legacy', '🏆', false, false, false),
('royal_dominion', 'Royal Dominion', 35000, 'premium', 'epic', 'royal_dominion', '🗡️', false, false, false),
('diamond_crown', 'Diamond Crown', 40000, 'legendary', 'legendary', 'diamond_crown', '💎', true, true, false),
('empire_rise', 'Empire Rise', 40000, 'legendary', 'legendary', 'empire_rise', '🏰', true, false, false),
('crown_eclipse', 'Crown Eclipse', 40000, 'legendary', 'legendary', 'crown_eclipse', '🌑', true, false, false),
('royal_dynasty', 'Royal Dynasty', 40000, 'legendary', 'legendary', 'royal_dynasty', '👑', true, false, false),
('crown_storm', 'Crown Storm', 50000, 'legendary', 'legendary', 'crown_storm', '⛈️', true, false, false),
('royal_inferno', 'Royal Inferno', 50000, 'legendary', 'legendary', 'royal_inferno', '🔥', true, false, false),
('crown_supernova', 'Crown Supernova', 50000, 'legendary', 'legendary', 'crown_supernova', '🌟', true, false, false),
('global_spotlight', 'Global Spotlight', 60000, 'legendary', 'legendary', 'global_spotlight', '🔦', true, false, true),
('kingdom_arrival', 'Kingdom Arrival', 60000, 'legendary', 'legendary', 'kingdom_arrival', '🏰', true, false, false),
('royal_blizzard', 'Royal Blizzard', 60000, 'legendary', 'legendary', 'royal_blizzard', '❄️', true, false, false),
('crown_solstice', 'Crown Solstice', 75000, 'legendary', 'legendary', 'crown_solstice', '☀️', true, false, false),
('royal_coronation', 'Royal Coronation', 75000, 'legendary', 'legendary', 'royal_coronation', '👑', true, false, false),
('crown_armada', 'Crown Armada', 75000, 'legendary', 'legendary', 'crown_armada', '⛵', true, false, false),
('infinite_crown', 'Infinite Crown', 100000, 'legendary', 'legendary', 'infinite_crown', '♾️', true, true, false),
('royal_celestial', 'Royal Celestial', 100000, 'legendary', 'legendary', 'royal_celestial', '🌠', true, false, false),
('golden_empire', 'Golden Empire', 100000, 'legendary', 'legendary', 'golden_empire', '🏛️', true, false, false),
('crown_vortex', 'Crown Vortex', 100000, 'legendary', 'legendary', 'crown_vortex', '🌀', true, false, false),
('legendary_crown', 'Legendary Crown', 150000, 'legendary', 'legendary', 'legendary_crown', '🌟', true, false, false),
('royal_heavens', 'Royal Heavens', 150000, 'legendary', 'legendary', 'royal_heavens', '☁️', true, false, false),
('crown_of_kings', 'Crown of Kings', 150000, 'legendary', 'legendary', 'crown_of_kings', '👑', true, false, false),
('crown_of_eternity', 'Crown of Eternity', 200000, 'mythic', 'mythic', 'crown_of_eternity', '♾️', true, true, false),
('divine_throne', 'Divine Throne', 250000, 'mythic', 'mythic', 'divine_throne', '🪑', true, false, false),
('golden_universe', 'Golden Universe', 300000, 'mythic', 'mythic', 'golden_universe', '🌌', true, false, false),
('royal_godform', 'Royal Godform', 400000, 'mythic', 'mythic', 'royal_godform', '✨', true, false, false),
('crown_of_worlds', 'Crown of Worlds', 500000, 'mythic', 'mythic', 'crown_of_worlds', '🌍', true, false, true),
('celestial_dynasty', 'Celestial Dynasty', 600000, 'mythic', 'mythic', 'celestial_dynasty', '🌠', true, false, false),
('crown_ouroboros', 'Crown Ouroboros', 700000, 'mythic', 'mythic', 'crown_ouroboros', '🐉', true, false, false),
('immortal_throne', 'Immortal Throne', 800000, 'mythic', 'mythic', 'immortal_throne', '🪑', true, false, false),
('crown_of_creation', 'Crown of Creation', 900000, 'mythic', 'mythic', 'crown_of_creation', '🌟', true, false, false),
('god_emperor_crown', 'God Emperor Crown', 1000000, 'mythic', 'mythic', 'god_emperor_crown', '👑', true, true, false)
on conflict (id) do update set
  name = excluded.name,
  shekel_cost = excluded.shekel_cost,
  tier = excluded.tier,
  rarity = excluded.rarity,
  animation_type = excluded.animation_type,
  icon = excluded.icon,
  visibility_boost = excluded.visibility_boost,
  trending = excluded.trending,
  top_pick = excluded.top_pick;