INSERT INTO public.gifts (id, name, shekel_cost, tier, rarity, animation_type, icon, visibility_boost, trending, top_pick, active) VALUES
('royal_coin_toss','Royal Coin Toss',100,'low','common','royal_coin_toss','',false,false,false,true),
('crown_spark','Crown Spark',200,'low','common','crown_spark','',false,true,false,true),
('gold_dust','Gold Dust',300,'low','common','gold_dust','',false,false,false,true),
('royal_clap','Royal Clap',300,'low','common','royal_clap','',false,false,false,true),
('mini_gem','Mini Gem',500,'low','common','mini_gem','',false,false,false,true),
('royal_scroll','Royal Scroll',500,'low','common','royal_scroll','',false,false,false,true),
('golden_rose','Golden Rose',500,'low','common','golden_rose','',false,false,true,true),
('court_applause','Court Applause',700,'low','rare','court_applause','',false,false,false,true),
('crown_wink','Crown Wink',700,'low','rare','crown_wink','',false,false,false,true),
('little_scepter','Little Scepter',900,'low','rare','little_scepter','',false,false,false,true),
('velvet_ribbon','Velvet Ribbon',900,'low','rare','velvet_ribbon','',false,false,false,true),
('gold_feather','Gold Feather',900,'low','rare','gold_feather','',false,false,false,true),
('royal_seal','Royal Seal',900,'low','rare','royal_seal','',false,false,false,true),
('purple_sparkle','Purple Sparkle',900,'low','rare','purple_sparkle','',false,false,false,true),
('mini_crown_pin','Mini Crown Pin',900,'low','rare','mini_crown_pin','',false,false,false,true),
('palace_bell','Palace Bell',900,'low','rare','palace_bell','',false,false,false,true),
('golden_cup','Golden Cup',900,'low','rare','golden_cup','',false,false,false,true),
('jewel_drop','Jewel Drop',900,'low','rare','jewel_drop','',false,false,false,true),
('royal_token','Royal Token',900,'low','rare','royal_token','',false,false,false,true),
('noble_flame','Noble Flame',900,'low','rare','noble_flame','',false,false,false,true),
('golden_flame','Golden Flame',1000,'popular','rare','golden_flame','',false,true,false,true),
('crown_burst','Crown Burst',1000,'popular','rare','crown_burst','',false,false,false,true),
('coin_rain','Coin Rain',2000,'popular','rare','coin_rain','',false,false,false,true),
('mini_crown_drop','Mini Crown Drop',2000,'popular','rare','mini_crown_drop','',false,false,false,true),
('royal_banner','Royal Banner',3000,'popular','rare','royal_banner','',false,false,false,true),
('treasure_chest','Treasure Chest',3500,'popular','rare','treasure_chest','',false,false,true,true),
('gold_ribbon','Gold Ribbon',5000,'popular','rare','gold_ribbon','',false,false,false,true),
('royal_fireworks','Royal Fireworks',5000,'popular','rare','royal_fireworks','',false,true,false,true),
('crown_pulse','Crown Pulse',5000,'popular','rare','crown_pulse','',false,false,false,true),
('kings_cup','King’s Cup',5000,'popular','rare','kings_cup','',false,false,false,true),
('queens_mirror','Queen’s Mirror',5000,'popular','rare','queens_mirror','',false,false,false,true),
('purple_torch','Purple Torch',7000,'popular','rare','purple_torch','',false,false,false,true),
('gold_lion','Gold Lion',7000,'popular','rare','gold_lion','',false,false,false,true),
('royal_trumpets','Royal Trumpets',7000,'popular','rare','royal_trumpets','',false,false,false,true),
('diamond_scroll','Diamond Scroll',7000,'popular','rare','diamond_scroll','',false,false,false,true),
('noble_shield','Noble Shield',9000,'popular','rare','noble_shield','',false,false,false,true),
('crown_beacon','Crown Beacon',9000,'popular','rare','crown_beacon','',false,false,false,true),
('palace_key','Palace Key',9000,'popular','rare','palace_key','',false,false,false,true),
('golden_laurel','Golden Laurel',9000,'popular','rare','golden_laurel','',false,false,false,true),
('royal_orb','Royal Orb',9000,'popular','rare','royal_orb','',false,false,false,true),
('throne_spark','Throne Spark',9000,'popular','rare','throne_spark','',false,false,false,true),
('crown_fire_trail','Crown Fire Trail',9000,'popular','rare','crown_fire_trail','',false,false,false,true),
('royal_halo','Royal Halo',9000,'popular','rare','royal_halo','',false,false,false,true),
('gem_crown_flash','Gem Crown Flash',9000,'popular','rare','gem_crown_flash','',false,false,false,true),
('regal_starfall','Regal Starfall',9000,'popular','rare','regal_starfall','',false,false,false,true),
('golden_wings','Golden Wings',10000,'premium','epic','golden_wings','',false,false,false,true),
('throne_room','Throne Room',10000,'premium','epic','throne_room','',false,true,false,true),
('royal_armor','Royal Armor',15000,'premium','epic','royal_armor','',false,false,false,true),
('golden_aura','Golden Aura',15000,'premium','epic','golden_aura','',false,false,false,true),
('crown_ascension','Crown Ascension',15000,'premium','epic','crown_ascension','',false,false,false,true),
('throne_rise','Throne Rise',20000,'premium','epic','throne_rise','',false,false,false,true),
('royal_guard','Royal Guard',20000,'premium','epic','royal_guard','',false,false,false,true),
('crown_steal_attempt','Crown Steal Attempt',25000,'premium','epic','crown_steal_attempt','',false,false,true,true),
('scepter_strike','Scepter Strike',25000,'premium','epic','scepter_strike','',false,false,false,true),
('diamond_flame','Diamond Flame',25000,'premium','epic','diamond_flame','',false,false,false,true),
('royal_phoenix','Royal Phoenix',30000,'premium','epic','royal_phoenix','',false,false,false,true),
('palace_gates','Palace Gates',30000,'premium','epic','palace_gates','',false,false,false,true),
('gold_dragon','Gold Dragon',30000,'premium','epic','gold_dragon','',false,false,false,true),
('purple_empire_flag','Purple Empire Flag',30000,'premium','epic','purple_empire_flag','',false,false,false,true),
('kings_decree','King’s Decree',35000,'premium','epic','kings_decree','',false,false,false,true),
('queens_blessing','Queen’s Blessing',35000,'premium','epic','queens_blessing','',false,false,false,true),
('crown_thunder','Crown Thunder',35000,'premium','epic','crown_thunder','',false,false,false,true),
('royal_meteor','Royal Meteor',35000,'premium','epic','royal_meteor','',false,false,false,true),
('jewel_storm','Jewel Storm',39000,'premium','epic','jewel_storm','',false,false,false,true),
('crown_portal','Crown Portal',39000,'premium','epic','crown_portal','',false,false,false,true),
('golden_chariot','Golden Chariot',39000,'premium','epic','golden_chariot','',false,false,false,true),
('royal_eclipse','Royal Eclipse',39000,'premium','epic','royal_eclipse','',false,false,false,true),
('crown_fortress','Crown Fortress',39000,'premium','epic','crown_fortress','',false,false,false,true),
('imperial_flame','Imperial Flame',39000,'premium','epic','imperial_flame','',false,false,false,true),
('royal_command','Royal Command',39000,'premium','epic','royal_command','',false,false,false,true),
('diamond_crown','Diamond Crown',40000,'legendary','legendary','diamond_crown','',true,true,false,true),
('crown_storm','Crown Storm',50000,'legendary','legendary','crown_storm','',true,false,false,true),
('global_spotlight','Global Spotlight',60000,'legendary','legendary','global_spotlight','',true,false,true,true),
('kingdom_arrival','Kingdom Arrival',75000,'legendary','legendary','kingdom_arrival','',true,false,false,true),
('royal_coronation','Royal Coronation',75000,'legendary','legendary','royal_coronation','',true,false,false,true),
('crown_armada','Crown Armada',75000,'legendary','legendary','crown_armada','',true,false,false,true),
('golden_empire','Golden Empire',100000,'legendary','legendary','golden_empire','',true,false,false,true),
('crown_vortex','Crown Vortex',100000,'legendary','legendary','crown_vortex','',true,false,false,true),
('infinite_crown','Infinite Crown',100000,'legendary','legendary','infinite_crown','',true,true,false,true),
('royal_celestial','Royal Celestial',100000,'legendary','legendary','royal_celestial','',true,false,false,true),
('legendary_crown','Legendary Crown',150000,'legendary','legendary','legendary_crown','',true,false,false,true),
('royal_heavens','Royal Heavens',150000,'legendary','legendary','royal_heavens','',true,false,false,true),
('crown_of_kings','Crown of Kings',150000,'legendary','legendary','crown_of_kings','',true,false,false,true),
('crown_of_queens','Crown of Queens',150000,'legendary','legendary','crown_of_queens','',true,false,false,true),
('royal_dynasty','Royal Dynasty',150000,'legendary','legendary','royal_dynasty','',true,false,false,true),
('empire_rise','Empire Rise',150000,'legendary','legendary','empire_rise','',true,false,false,true),
('crown_eclipse','Crown Eclipse',150000,'legendary','legendary','crown_eclipse','',true,false,false,true),
('eternal_palace','Eternal Palace',150000,'legendary','legendary','eternal_palace','',true,false,false,true),
('royal_sunburst','Royal Sunburst',150000,'legendary','legendary','royal_sunburst','',true,false,false,true),
('infinite_throne','Infinite Throne',150000,'legendary','legendary','infinite_throne','',true,false,false,true),
('crown_of_eternity','Crown of Eternity',200000,'mythic','mythic','crown_of_eternity','',true,true,false,true),
('divine_throne','Divine Throne',250000,'mythic','mythic','divine_throne','',true,false,false,true),
('golden_universe','Golden Universe',300000,'mythic','mythic','golden_universe','',true,false,false,true),
('royal_godform','Royal Godform',400000,'mythic','mythic','royal_godform','',true,false,false,true),
('crown_of_worlds','Crown of Worlds',500000,'mythic','mythic','crown_of_worlds','',true,false,true,true),
('celestial_dynasty','Celestial Dynasty',600000,'mythic','mythic','celestial_dynasty','',true,false,false,true),
('crown_ouroboros','Crown Ouroboros',700000,'mythic','mythic','crown_ouroboros','',true,false,false,true),
('immortal_throne','Immortal Throne',800000,'mythic','mythic','immortal_throne','',true,false,false,true),
('crown_of_creation','Crown of Creation',900000,'mythic','mythic','crown_of_creation','',true,false,false,true),
('god_emperor_crown','God Emperor Crown',1000000,'mythic','mythic','god_emperor_crown','',true,true,false,true)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  shekel_cost = EXCLUDED.shekel_cost,
  tier = EXCLUDED.tier,
  rarity = EXCLUDED.rarity,
  animation_type = EXCLUDED.animation_type,
  icon = EXCLUDED.icon,
  visibility_boost = EXCLUDED.visibility_boost,
  trending = EXCLUDED.trending,
  top_pick = EXCLUDED.top_pick,
  active = true;