// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { runtimeConfig } from '@/lib/runtimeConfig';
import type { Database } from './types';

// createClient throws during module evaluation when configuration is absent.
// Valid fallbacks keep imports safe while main.tsx renders a visible outage UI.
const SUPABASE_URL = runtimeConfig.isValid
  ? runtimeConfig.supabaseUrl
  : "https://configuration.invalid";
const SUPABASE_PUBLISHABLE_KEY = runtimeConfig.isValid
  ? runtimeConfig.supabasePublishableKey
  : "configuration-missing";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
